# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r:
  - bioc-devel
  - bioc-release
  - release
  - devel
  - 3.4.0
r_github_packages:
  - tidyverse/magrittr
  - Rdatatable/data.table
  - r-lib/testthat
r_packages:
  - covr
bioc_packages:
  - BiocInstaller
  - IRanges
  - GenomicRanges
env:
  - MC_CORES=2 OMP_NUM_THREADS=2 DISPLAY=:1
warnings_are_errors: true
r_check_args: ""
sudo: true
repos:
  CRAN: https://cloud.r-project.org
after_success:
  - Rscript -e 'library(covr); codecov()'
notifications:
  email:
    on_success: always
    recipients:
      - andrewrech@gmail.com
      - Leepr@upenn.edu
